const sections = [
  {
    title: "Skin",
    symptoms: [
      "Itching",
      "Skin rash",
      "Nodal skin eruptions",
      "Redness of eyes",
      "Patches in throat",
      "Yellowish skin",
      "Drying and tingling lips",
      "Skin peeling",
      "Silver-like dusting",
      "Small dents in nails",
      "Inflammatory nails",
      "Blister",
      "Red sore around nose",
      "Yellow crust ooze",
      "Pus-filled pimples",
      "Blackheads",
      "Scarring",
    ],
  },
  {
    title: "Eyes",
    symptoms: [
      "Sunken eyes",
      "Blurred and distorted vision",
      "Redness of eyes",
      "Watering from eyes",
      "Visual disturbances",
      "Loss of smell",
    ],
  },
  {
    title: "Head & Neck",
    symptoms: [
      "Headache",
      "Pain behind the eyes",
      "Stiff neck",
      "Neck pain",
      "Dizziness",
      "Slurred speech",
      "Loss of balance",
      "Unsteadiness",
      "Spinning movements",
    ],
  },
  {
    title: "Mouth & Throat",
    symptoms: [
      "Ulcers on tongue",
      "Patches in throat",
      "Sore throat",
      "Throat irritation",
    ],
  },
  {
    title: "Digestive System",
    symptoms: [
      "Stomach pain",
      "Acidity",
      "Vomiting",
      "Burning micturition",
      "Indigestion",
      "Nausea",
      "Loss of appetite",
      "Abdominal pain",
      "Diarrhoea",
      "Constipation",
      "Pain during bowel movements",
      "Pain in anal region",
      "Bloody stool",
      "Irritation in anus",
      "Belly pain",
      "Abnormal menstruation",
      "Passage of gases",
    ],
  },
  {
    title: "Urinary System",
    symptoms: [
      "Burning micturition",
      "Spotting urination",
      "Yellow urine",
      "Yellowing of eyes",
      "Fluid overload",
      "Bladder discomfort",
      "Continuous feel of urine",
      "Foul smell of urine",
    ],
  },
  {
    title: "Circulatory System",
    symptoms: [
      "Sweating",
      "Dehydration",
      "Fluid overload",
      "Swelling of stomach",
      "Swelled lymph nodes",
      "Swollen legs",
      "Swollen blood vessels",
      "Prominent veins on calf",
      "Palpitations",
      "Fast heart rate",
      "Painful walking",
    ],
  },
  {
    title: "Respiratory System",
    symptoms: [
      "Continuous sneezing",
      "Cough",
      "Breathlessness",
      "Phlegm",
      "Chest pain",
      "Sinus pressure",
      "Runny nose",
      "Congestion",
      "Blood in sputum",
    ],
  },
  {
    title: "Musculoskeletal System",
    symptoms: [
      "Joint pain",
      "Muscle wasting",
      "Muscle pain",
      "Muscle weakness",
      "Knee pain",
      "Hip joint pain",
      "Stiff joints",
      "Swelling joints",
      "Weakness in limbs",
      "Painful walking",
      "Swollen extremities",
    ],
  },
  {
    title: "Endocrine System",
    symptoms: [
      "Weight gain",
      "Weight loss",
      "Anxiety",
      "Mood swings",
      "Restlessness",
      "Lethargy",
      "Irritability",
      "Excessive hunger",
      "Obesity",
      "Enlarged thyroid",
    ],
  },
  {
    title: "Nervous System",
    symptoms: [
      "Anxiety",
      "Restlessness",
      "Lethargy",
      "Mood swings",
      "Depression",
      "Slurred speech",
      "Loss of balance",
      "Spinning movements",
      "Weakness of one body side",
    ],
  },
  {
    title: "General Symptoms",
    symptoms: [
      "High fever",
      "Fatigue",
      "Weakness in limbs",
      "Malaise",
      "Weakness of one body side",
      "Lethargy",
      "Unsteadiness",
      "Cramps",
      "Bruising",
      "Obesity",
      "Puffy face and eyes",
      "Drying and tingling lips",
      "Lack of concentration",
      "Distention of abdomen",
    ],
  },
  {
    title: "Other Symptoms",
    symptoms: [
      "Blurred and distorted vision",
      "Irregular sugar level",
      "Red spots over body",
      "Polyuria",
      "Receiving blood transfusion",
      "Receiving unsterile injections",
      "Stomach bleeding",
      "Spinning movements",
    ],
  },
];
export default sections;
